### ISSUE TITLE
JFX: Menu entries are not correctly found

### ISSUE THREAD

**Issue by mirceade** [renatoathaydes/Automaton#28] opened 2015-08-06 09:01 UTC
In JavaFx apps, "clicking" on a menu entry works but clicking on the resulting sub-menu items doesn't.
JRE 8 - u 51

**Comment by renatoathaydes** [comment] 2015-08-06 09:16
Which selector did you try when selecting the sub-menu items? `text:`, `type:` or some complex selector?

**Comment by mirceade** [comment] 2015-08-06 09:19
It was "text:" but I'll double check to see if it wasn't more than one component with that text on the screen at that moment.

**Comment by renatoathaydes** [comment] 2015-08-06 09:23
Please make sure to use a good "narrowing" selector, something like `matchingAll( "type:MenuItem", "text:My Text" )`. If this does not work right, I'll have a look, it's possible the search algorithm missed something.

**Comment by mirceade** [comment] 2015-08-06 11:04
We've tried it with the id selection fxer.clickOn("#aboutMenuItem") and it DOES move the mouse near the element but not on the element. It also could be clicking outside it.

We've also tried with a selector: fxer.clickOn(matchingAll("type:MenuItem", "text:About")) and it does not work because we get an exception like this:
com.athaydes.automaton.GuiItemNotFound: Could not locate ComplexSelector(matchType:ALL,queries:[type:MenuItem, text:About]) 

Doing fxer.getAt("#aboutMenuItem") to get a reference of the element works but fxer.getAt(matchingAll("type:MenuItem", "text:About")) throws the same exception:

com.athaydes.automaton.GuiItemNotFound: Could not locate ComplexSelector(matchType:ALL,queries:[type:MenuItem, text:About])

**Comment by renatoathaydes** [comment] 2015-08-06 11:07
Ok, thank you for all the details. I will fix this as soon as I can. Should release a fix in a few days.

**Comment by renatoathaydes** [comment] 2015-08-06 18:25
Confirmed the bug. The y-coordinate of the menuItem is incorrect. Affects Java 7 and Java 8.

**Comment by renatoathaydes** [comment] 2015-08-06 18:53
This bug was caused by a workaround for a JavaFX bug in which the Scene's position was reported incorrectly.

You can remove that workaround by running the following Groovy code in the same JVM where your tests will run:

```groovy
com.athaydes.automaton.FXAutomaton.metaClass.static.getScenePosition = { Node node ->
    new Point( node.scene.x as int, node.scene.y as int )
}
```

I will publish a fix for this soon, if you prefer to wait.

**Comment by mirceade** [comment] 2015-08-06 18:56
Hi, we will wait for a proper release because we've already implemented a quite fragile workaround: clicking based on relative coordinates. 
Thank you for your effort!

**Comment by renatoathaydes** [comment] 2015-08-06 21:07
Released the fix. Change your Automaton version to 1.2.2.

**Closed by renatoathaydes** 2015-08-06 21:07 UTC
Labels: bug

**Comment by mirceade** [comment] 2015-08-07 07:45
Fix confirmed.
