### ISSUE TITLE
Issue with Java 8u20

### ISSUE THREAD

**Issue by fabriziocucci** [renatoathaydes/Automaton#23] opened 2014-10-07 18:07 UTC
Hi guys,

I'm trying to run this simple test:

```
	private Swinger swinger;

	@Before
	public void setup() {
		FXApp.startApp(new UriParserMain());
		swinger = Swinger.forSwingWindow();
	}

	@Test
	public void testFeature() {
		swinger.clickOn("#uriTextField").type("Hello Automaton!");
	}
```

but I get the following exception with Java 8u20:

```
java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    com/athaydes/internal/interceptor/ToFrontInterceptor.<init>(Ljava/lang/Class;)V @63: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: b800 144d 04bd 0016 5903 2b53 5910 ff12
    0x0000010: 04b8 001c 2a5f ab00 0000 0042 0000 0002
    0x0000020: b3b9 4b79 0000 001a e4d2 7468 0000 002f
    0x0000030: 5f5a 5903 3212 1eb8 0022 c000 1e5f 57b7
    0x0000040: 0025 a700 205f 5a59 0332 b800 2bc0 002d
    0x0000050: 5f57 b700 2fa7 000d bb00 3159 1233 b700
    0x0000060: 36bf 572c 1237 322a b900 3d02 0057 b1  
  Stackmap Table:
    full_frame(@48,{UninitializedThis,Object[#45],Object[#67]},{Object[#69],UninitializedThis})
    full_frame(@69,{UninitializedThis,Object[#45],Object[#67]},{Object[#69],UninitializedThis})
    full_frame(@88,{UninitializedThis,Object[#45],Object[#67]},{Object[#69],UninitializedThis})
    full_frame(@98,{Object[#2],Object[#45],Object[#67]},{Object[#69]})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at org.codehaus.groovy.reflection.CachedClass$2$1.run(CachedClass.java:69)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:66)
	at org.codehaus.groovy.reflection.CachedClass$2.initValue(CachedClass.java:64)
	at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
	at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
	at org.codehaus.groovy.reflection.CachedClass.getConstructors(CachedClass.java:258)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:189)
	at groovy.lang.MetaClassImpl.<init>(MetaClassImpl.java:193)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createNormalMetaClass(MetaClassRegistry.java:158)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.createWithCustomLookup(MetaClassRegistry.java:148)
	at groovy.lang.MetaClassRegistry$MetaClassCreationHandle.create(MetaClassRegistry.java:131)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:209)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:241)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:255)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:859)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at com.athaydes.automaton.FXApp.initializeToFrontInterceptor(FXAutomaton.groovy:173)
	at com.athaydes.automaton.FXApp.initialize(FXAutomaton.groovy:136)
	at com.athaydes.automaton.FXApp.startApp(FXAutomaton.groovy:195)
	at Automation.setup(Automation.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Is there a problem in my code or the library cannot be used with Java 8u20?

Thanks,
Fabrizio

**Comment by psyren89** [comment] 2015-01-05 04:14
Also having this issue. Any news regarding the new Groovy version?

**Comment by renatoathaydes** [comment] 2015-01-05 09:55
It turns out Groovy cannot fix this.... it's the new Java 8 version that you need. Can you please try Java 8_u25 and confirm that it works?

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by psyren89** [comment] 2015-01-06 00:58
That's the version I'm currently using. I'm on OSX, if that matters.
![] (http://puu.sh/e7ZoL/7d28eff4a4.png)

**Comment by renatoathaydes** [comment] 2015-01-06 09:11
Is the Exception you get the same as shown in the original issue here? OS X support has not been completed yet. I am actually looking for help with that. Would you be interested in helping (mostly making small changes in the code, which I can help with, and testing)?

Anyway, I will try on Linux and Windows later, as I expected Java 8 update 25 to work.

**Comment by renatoathaydes** [comment] 2015-01-08 17:45
I can confirm that Automaton runs fine with Java 1.8.25 and Groovy 2.3.3+, with all tests passing!

As expected, Oracle made changes to the compiler Verifier so that Java 8 and Groovy work well together again (and other JVM tools like JRebel also).

**Comment by psyren89** [comment] 2015-01-11 23:08
Depending on what's involved, I may not really be of much use when it comes to diagnosing and fixing OSX specific quirks as I don't have a lot of experience or knowledge in this area.

In the meantime, I can set up a Windows VM to run the tests. Thanks for your help!

**Comment by renatoathaydes** [comment] 2015-02-26 22:41
Just wanted to make it clear: Automaton works well with the latest versions of Java 7 (update 70+) and Java 8 (update 25+). Tested in Windows and Linux.

This means that Automaton/Groovy only had issues for a brief period, with Java 7 update 64 (I think) and Java 8 updates 11 and 20. Anything else works. Closing this issue as it should no longer be a problem.

**Closed by renatoathaydes** 2015-02-26 22:41 UTC
